package constant

//放环境变量名。

const (
	EnvKeyPort                             = "PORT"
	EnvKeyDBDriver                         = "DB_DRIVER"
	EnvKeyJWTSecret                        = "JWT_SECRET"
	EnvKeyTokenDuration                    = "TOKEN_DURATION"
	EnvKeyRefreshTokenDuration             = "REFRESH_TOKEN_DURATION"
	EnvKeyRefreshTokenDurationWithRemember = "REFRESH_TOKEN_DURATION_WITH_REMEMBER"
	EnvKeyEnableRegister                   = "ENABLE_REGISTER"
	EnvKeyRootAdminUsername                = "ROOT_ADMIN_USERNAME"
	EnvKeyRootAdminEmail                   = "ROOT_ADMIN_EMAIL"
	EnvKeyRootAdminPassword                = "ROOT_ADMIN_PASSWORD"
	EnvKeyCaptchaProvider                  = "CAPTCHA_PROVIDER"
	EnvKeyCaptchaDevPasscode               = "CAPTCHA_DEV_PASSCODE"
	EnvKeyCaptchaSiteKey                   = "CAPTCHA_SITE_KEY"
	EnvKeyCaptchaSecretKey                 = "CAPTCHA_SECRET_KEY"
	EnvKeyCaptchaURL                       = "CAPTCHA_URL"
	EnvKeyDBSQLitePath                     = "DB_SQLITE_PATH"
	EnvKeyDBHost                           = "DB_HOST"
	EnvKeyDBPort                           = "DB_PORT"
	EnvKeyDBUser                           = "DB_USER"
	EnvKeyDBPassword                       = "DB_PASSWORD"
	EnvKeyDBName                           = "DB_NAME"
	EnvKeyDBSSLMode                        = "DB_SSL_MODE"
	EnvKeyMode                             = "MODE"
	EnvKeyEmailEnable                      = "EMAIL_ENABLE"
	EnvKeyEmailUsername                    = "EMAIL_USERNAME"
	EnvKeyEmailPassword                    = "EMAIL_PASSWORD"
	EnvKeyEmailAddress                     = "EMAIL_ADDRESS"
	EnvKeyEmailHost                        = "EMAIL_HOST"
	EnvKeyEmailPort                        = "EMAIL_PORT"
	EnvKeyEmailSSL                         = "EMAIL_SSL"
	EnvKeyEnableEmailVerify                = "ENABLE_EMAIL_VERIFY"
	EnvKeyRedisAddr                        = "REDIS_ADDR"
	EnvKeyRedisPassword                    = "REDIS_PASSWORD"
	EnvKeyRedisDB                          = "REDIS_DB"
)
